### ISSUE TITLE
確認待ち画面で入力の取り消しを行う

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/stuffy-ios#2]
現状入力値の修正は可能ですが、取り消しができない。
注文データの選択自体を間違えた時のために取り消しもできるようにしたい。

取り消したデータは、着荷一覧に戻るようにお願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました。バージョン 1.0 (13)でご確認ください。
取り消しは左スワイプで動いてます

**Comment by take-iwa** [comment]
バッチリです。ログアウトもOK
